I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name u'start' is defined twice, at game/script.rpy:11 and game/scripts/script.rpy:11.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/danielgadarve/Downloads/renpy-6.99.11-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/Users/danielgadarve/Downloads/renpy-6.99.11-sdk/renpy/main.py", line 358, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/Users/danielgadarve/Downloads/renpy-6.99.11-sdk/renpy/script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/Users/danielgadarve/Downloads/renpy-6.99.11-sdk/renpy/script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "/Users/danielgadarve/Downloads/renpy-6.99.11-sdk/renpy/script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'start' is defined twice, at game/script.rpy:11 and game/scripts/script.rpy:11.

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.11.1749
 
